let formulario = document.getElementById('formulario')
let nome = document.getElementById('nome')
let email = document.getElementById('email')
let celular = document.getElementById('cel')
let senha = document.getElementById('sen')
let csenha = document.getElementById('csen')
